import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import ISA

# import python files as modules
import flaps
import matching_diagram


# 1 - get preliminary wing planform design

df = pd.read_excel('wing_initial_planform.xlsx')
wing_unclean = df.set_index('Parameter')['value'].to_dict()
wing = {}
for key, value in wing_unclean.items():
    try:
        wing[key] = float(value)
    except (ValueError, TypeError): # for strings or blanks
        wing[key] = value  

# print(wing)

# 2 - append all design choices

wing["choices"] = {
    "flap_type": "single slotted fowler flap"
}

# 3 - airfoil data input 

# Sample data generated by AI 
wing.update({
    "CL alpha clean": 0.113,    
    "CL max clean": 1.8,           
    "a0L": -3.05,   # [deg]           
})


# 4 - iterative loop

# flaps.flaps_calculation(wing)
matching_diagram.get_wing_graph(wing)